### ISSUE TITLE
in __init__     self._handle = _dlopen(self._name, mode) OSError: [WinError 126] 找不到指定的模块。

### ISSUE THREAD

**Issue by papicheng** [TheImagingSource/IC-Imaging-Control-Samples#10]
when I run the tis-Opencv using pycharm on windows, it shows that "in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。" cannot find the module.
I looked for the solution of this problem, but nothing helpful for me. 
If someone could give me some advise, I will be very appreciated.

**Comment by TIS-Stefan** [comment]
Hello

I think, it is general Python issue you have there. It may also can be a Pycharm issue. You may try to find out, what self._name contains.
Can you run the program from command line, without PyCharm? 

BTW: I use Visual Studio Code for Python editing.

Stefan

**Comment by papicheng** [comment]
aha, running it from command line works, it's odd to use PyCharm. Thanks for your reply！
