### ISSUE TITLE
Is there any plan to support RGB64?

### ISSUE THREAD

**Issue by eehyc** [TheImagingSource/IC-Imaging-Control-Samples#11]
Hello. For now, the SnapImage() function can only capture RGB32 and Y16 formats. Is there any way to get 12bit RGB images? For example, can I decode the buffer to a 12bit RGB format in the FrameReadyCallback() function?

Thank you!

**Comment by TIS-Stefan** [comment]
Hello

You must debayer the Y16 format  to RGB64 on your own.  Maybe there is an OpenCV function. 

Stefan
