### ISSUE TITLE
Line 725 in tisgrabber.py has an unresolved reference at IC.ImageFileTypes

### ISSUE THREAD

**Issue by somtooo** [TheImagingSource/IC-Imaging-Control-Samples#13]
return TIS_GrabberDLL.SaveImage(self._handle, self.s(FileName),IC.ImageFileTypes[self.s(FileType)],Quality)

**Comment by TIS-Stefan** [comment]
Aha.
Do you have some more context, e.g. a sample code for me, so I can reproduce that? That will be helpful.

**Comment by somtooo** [comment]
Hello, 
Thanks for the reply. Forgot to mention im working with your python code. Secondly i didnt get the error by running the code instead I am getting a can not load dll file error.

 I just pulled from github and figured out my IDE had an error notification.
![github](https://user-images.githubusercontent.com/19388476/67313863-58fb9f80-f4c9-11e9-8f10-ce571620f624.JPG). To reproduce error just pull code. Go to tisgrabber.py line 725.

 But this might just be because i use an ide i doubt a code editor will pick that up
