### ISSUE TITLE
Trying to load tisgrabber.dll gives me windows error

### ISSUE THREAD

**Issue by somtooo** [TheImagingSource/IC-Imaging-Control-Samples#14]
Ive tried editing the path- C:\\Users\\aaron\\PycharmProjects\\untitled\\tisgrabber_x64.dll
Still didnt work. Im i meant to do anything before trying to import. Thanks

WindowsError: [Error 126] The specified module could not be found

**Comment by TIS-Stefan** [comment]
The TISUDSHL11_64.dll must by copied too.

Stefan

**Comment by somtooo** [comment]
Hello, 
Thanks for the reply, I forgot to say im working with the python code. Also all dll files are in my directory. Find attached a picture of my directory
![github](https://user-images.githubusercontent.com/19388476/67313606-dc68c100-f4c8-11e9-9efe-78258bc201c4.JPG)

**Comment by somtooo** [comment]
For more info 
This is code i ran which produced the error
![code](https://user-images.githubusercontent.com/19388476/67314698-cbb94a80-f4ca-11e9-89c0-473ce165fdcb.JPG)

This is the error
![error](https://user-images.githubusercontent.com/19388476/67314729-d7a50c80-f4ca-11e9-9f9b-eb4400f44c87.JPG)

This is where the dll file gets loaded.
![dlll](https://user-images.githubusercontent.com/19388476/67314814-eee3fa00-f4ca-11e9-8b29-e43ecfc27869.JPG)

**Comment by TIS-Stefan** [comment]
Hello
I am clueless. It work on all other computers, thus there must be a different issue. 
Your working directory is "c:\users\aaron\pycharmproject\untitled"? I do not know, how PyCharm sets the working directory. (I do not use PyCharm.)
You may open a command line window (cmd.exe), change into that directory and start the script:

```
>cd c:\users\aaron\pycharmproject\untitled
>pyhton webcamtest.py
```
Annotation: That will work with The Imaging Source cameras only.

Stefan

**Comment by somtooo** [comment]
Hello,
Thanks  for the reply. Which text editor do you use. And yes im working on a project for Dwyer Instruments. The company recently purchased an Imaging Source camera

**Comment by TIS-Stefan** [comment]
Hello

I use Visual Studio Code in Linux and Windows. However, Pycharm should work too, it is, from my point of view only a matter, whether the DLLs are in the working directory or in the windows search path. So you may set the working directory in the PyCharm project settings, if there is a setting like that.

Have you been able to run your Python script from command line, as I suggested? What happened?

Stefan

**Comment by somtooo** [comment]
Hello good day,
I got this when i ran from cmd
![github](https://user-images.githubusercontent.com/19388476/67594270-965e6800-f729-11e9-8fe6-0e6262e90afe.JPG)

**Comment by somtooo** [comment]
But then i choose device name and it closes

**Comment by TIS-Stefan** [comment]
Which camera model do you use? The library works with The Imaging Source cameras only.

Did you try IC Capture to, in order to make sure your camera works fine? It can be downloaded from https://www.theimagingsource.com/support/downloads-for-windows/end-user-software/iccapture/

Stefan

**Comment by somtooo** [comment]
The device name is an image source camera. And i already tested the camera with the software. Works fine with very good quality.

**Comment by TIS-Stefan** [comment]
And if you click on the combo box to get its items, nothing is shown?
Which software did you try?
What is the exact model name of your camera?

**Comment by somtooo** [comment]
Hello,
This is the combo box,
![github](https://user-images.githubusercontent.com/19388476/68036153-230da680-fc93-11e9-8868-17d29c518204.JPG)

This is the software i use 
![iccapture](https://user-images.githubusercontent.com/19388476/68036202-3d478480-fc93-11e9-9690-c6747c7a7a7b.JPG)

Software works with camera very well just live video wont load with when i click ok on combo box

**Comment by somtooo** [comment]
am i meant to install any other sdk to my system?

**Comment by somtooo** [comment]
for more context here is a video of what happens


![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19388476/68040657-c44d2a80-fc9c-11e9-8dac-47e48296a7c4.gif)

**Comment by TIS-Stefan** [comment]
You program ends immediately after you started the live video. Therefore, the video ends immediately. You may add a while loop for keypress after you started the live video.

Stefan

**Comment by somtooo** [comment]
Hey,
I made it hold by doing this and was able to take a picture
![githubTest](https://user-images.githubusercontent.com/19388476/68160014-7e03ff80-ff18-11e9-8486-f4b0aa7abdcc.JPG)
And here is it
![zoom](https://user-images.githubusercontent.com/19388476/68160074-970cb080-ff18-11e9-9bc7-d2924cbaff11.JPG)
in the ic capture software i can zoom out to see the gauge perfectly. Is it possible to do the same here because moving the camera all the way back isnt an option for now and i need an image of the gauge. 
The camera is currently 15inches from the gauge. Will changing the lens work?
