### ISSUE TITLE
Gain property setting problem with IC Cameras

### ISSUE THREAD

**Issue by ljc19800331** [TheImagingSource/IC-Imaging-Control-Samples#16]
Hello, 

I am using the python API for the DFK 33UP1300 camera. When I run the "tis-OpenCV.py" demo code, it shows the error related to the "Camera.SetPropertyValue("Gain","Value",10)" line of code. I am not sure if this is a normal issue with the code or the camera hardware. This is the screen shot: 
![p1](https://user-images.githubusercontent.com/26176910/73585371-b7dc9780-446e-11ea-920f-b197de68926f.jpg)
![p2](https://user-images.githubusercontent.com/26176910/73585352-8c59ad00-446e-11ea-9e89-bd999782251b.jpg)

Thanks.

**Comment by TIS-Stefan** [comment]
Hello GuangShen

please check with the 
tcam-ctrl -p 34910523
whether it shows "Gain" property.
Also in the Python sample is an commented call to listproperties, you may enable that and check for Gain. 
Which computer do you use?

Thank you in advance!

Stefan

**Comment by TIS-Stefan** [comment]
Hello GuangShen

I just see, its Windows, not Linux.
The Gain range is  144 to  1200 . Therefore you get an error, if you try to set a value of 10.

Stefan
