### ISSUE TITLE
Pycharm searching file for tisgrabber_x64.dll

### ISSUE THREAD

**Issue by ljc19800331** [TheImagingSource/IC-Imaging-Control-Samples#17]
Hello, when I run the tisgrabber program in Pycharm I am getting the "[Error 126] The specified module could not be found" error. I have to change the working folder to that folder which contains the "tisgrabber_x64.dll" file. I am wondering if there is a faster way to load the .dll file without changing the working folder? Thanks.

**Comment by TIS-Stefan** [comment]
The clean solution is having always a correct working directory being specified.

Well.. The dirty solution is to copy the DLL into one of the directories stored in PATH environment, e.g. c:\windows\system32

Stefan

**Comment by ljc19800331** [comment]
Thanks for your help and the issue is caused by the wrong setting working repository in pycharm.
