### ISSUE TITLE
Python (tisgrabber) - how to stream without live preview?

### ISSUE THREAD

**Issue by gmoneyphx** [TheImagingSource/IC-Imaging-Control-Samples#40]
I am using the 32-trigger-callback example successfully with an external trigger.  How to stream camera data without the live preview (which in my use case just wastes system resources)?

**Comment by TIS-Stefan** [comment]
Hello

pass 0 as second parameter to IC_StartLive(grabber,0) instead of 1. 

Stefan

**Comment by gmoneyphx** [comment]
Thank you for your assistance and your efforts on this SDK.  It is very, very helpful.
