### ISSUE TITLE
SnapImage randomly timeout

### ISSUE THREAD

**Issue by takuro1026** [TheImagingSource/IC-Imaging-Control-Samples#46]
Hi team,

Thank you for your effort that provide us example, so we can develop based on it.
I have worked with your products over a year. Everything works smoothly. We use your products to create a motion related application for our customers.
However, I create this ticket because there is a thing raising my concern recently. Based on your example, I also used Pythonnet as bridge to utilize your library, so I can get the camera timestamp for further usage. I found out that there is a situation which rarely happen but I have seen few times already.  

Using snap sink and set timeout to 5 sec (just like your example); sometimes, the call will continuously timeout every few sec and this won't happen on just one camera, if I have multiple cameras connecting to the same machine, it also happen to other cameras as well.

The other case is cannot connect to camera (open camera), I have checked that no program is using the camera and IC Capture is not running.

Both cases are rarely to see but it happened few times to me; however, once I reboot the computer, then all issues gone. I wonder if you have seen those issues before? Is there any possible case that make those issues happen?

Thank you.

Best,

Takuro

Forgot to provide the device model I'm using right now. It's DFK33GX287.

**Comment by TIS-Stefan** [comment]
Hello Takuro

Thank you very much for your compliments!

> Using snap sink and set timeout to 5 sec (just like your example); sometimes, the call will continuously timeout every few sec and this won't happen on just one camera, if I have multiple cameras connecting to the same machine, it also happen to other cameras as well.
In this case, I can guess only: The camera is lost or the communication is disturbed extremely. Checking with Wireshark you could see, whether the camera still sends image data or not. That would be the first approach for debugging. 
In case you use a managed switch for connecting the cameras to your computer, please enable Data Flow Control on the ports, which connect to a camera and also disable power saving. 

> The other case is cannot connect to camera (open camera), I have checked that no program is using the camera and IC Capture is not running.
Was IC Capture able to open this camera in that situation? If not, was the camera listed in the "GigECam IP Config" program of the driver, in particular with correct IP address?

Best Regards

Stefan
