### ISSUE TITLE
ctypes.ArgumentError: Expected LP_HGRABBER instance instead of LP_HGRABBER

### ISSUE THREAD

**Issue by vandoitruong1997** [TheImagingSource/IC-Imaging-Control-Samples#48]
Dear sir,

First, I ran an example 41 without error, however if I close that application and run the program gain, I got a " ctypes.ArgumentError " as below figure:
![error](https://user-images.githubusercontent.com/48547512/161655324-cab0f0a4-f0c2-4e5c-aaa9-bdf68f114597.png)

Current solution: restart the kernel every time when running the program.
However, it's quite inconvenient,  could you please give me some suggestions to fix this problem? 
Thank you so much!

**Comment by vandoitruong1997** [comment]
Thank you for your reply!
I added your suggestion however it also occurred that problem.

I tried to add this line into the frameReadyCallback function:
print('thread index:', threading.get_ident(), "\n")
After exiting a program, Camera threads still exist and print out the thread index.
I think the IC_StopLive function could be a reason because it can not release camera.

**Comment by TIS-Stefan** [comment]
Hello

At end of your program you should call
`ic.IC_ReleaseGrabber(hGrabber)`

Stefan
