### ISSUE TITLE
Why "GetVideoFormats" doesn't show all avaiable modes?

### ISSUE THREAD

**Issue by luizmagnago** [TheImagingSource/IC-Imaging-Control-Samples#5]
If I use "ShowDeviceSelectionDialog" the Video Format List have a lot more option then when I use "GetVideoFormats" function. How do I get the list with all resolution and the binning options?

**Comment by PolarBean** [comment]
I have found it useful to get the options from IC-capture. if anybody else is curious as to how binning is enabled its through the SetVideoFormat command. 
`Camera.SetVideoFormat("Y800 (720x540)[Binning 2x]") `

**Comment by TIS-Stefan** [comment]
IC Capture create a list of some standard formats, e.g 320x240, 640x420,1024x728 and so from an internal hardcoded array of resolutions. IC Capture uses that arrays on cameras, that can have more or less any resolution, by taking care of step width in width and height. 

But your method is correct and the one, I recommend in the same situation. 

Stefan
