### ISSUE TITLE
Confusion about version of tisgrabber.dll

### ISSUE THREAD

**Issue by bleykauf** [TheImagingSource/IC-Imaging-Control-Samples#59]
I found that the `tisgrabber.*` files in the [python samples](https://github.com/TheImagingSource/IC-Imaging-Control-Samples/tree/master/Python/tisgrabber/samples) is not the same as in the latest version on the [website](https://www.theimagingsource.com/support/downloads-for-windows/software-development-kits-sdks/tisgrabberdll/) which is 3.4.0.51.

I assume that the library in the samples folder is 3.5 but I did not find any version information in `tisgrabber.h`. 

Could you please clarify this and possibly update the C library on the website or point me to the correct download link?

**Comment by bleykauf** [comment]
Thank you for the quick reply.

So I guess delivering the `.dll`s with custom software is the way to go here if I wanted to use version 3.5. How is the library licensed, i.e. is it permitted to deliver `tisgrabber.dll` for non-commercial open-source projects?

**Comment by TIS-Stefan** [comment]
The IC 3.5 Dlls can not be linked to tisgrabber. 3.4 only. 

The tisgrabber.dll as well as IC Imaging Control can be distributed for free for commercial and non commercial projects. 

Stefan
